/*DATA SCIENCE CAPSTONE*/
/*MICHAEL BASSETT*/ 

/*THIS IS THE SAS CODE THAT I USED FOR THE DATA CLEANING PHASE*/ 

/*IMPORT CODE TAKEN FROM SAS IMPORT WIZARD*/ 
PROC IMPORT OUT= WORK.yelp 
            DATAFILE= "FD.csv" 
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2; 
RUN;


/*BELOW I AM SETTING ALL OF THE NEW VARIABLES. FOR THE MOST PART, IF ITS TRUE THE VALUE IS 1, FALSE, THE VALUE IS 0, AND MISSING THE VALUE IS 2*/ 
DATA YELP2;
SET YELP;

/*ALCOHOL*/ 
IF ALCOHOL IN ("beer_and_wine","full_bar","u'beer_and_wine'","u'full_bar'") THEN ALCOHOL2=1;
IF ALCOHOL IN ('none',"u'none'") THEN ALCOHOL2=0;
IF ALCOHOL IN ('N/A','None') THEN ALCOHOL2=2;

/*ATTIRE*/
IF ATTIRE IN ("casual","u'casual'") THEN ATTIRE2=1;
IF ATTIRE IN ("dressy","formal","u'dressy'","u'formal'") THEN ATTIRE2=0;
IF ATTIRE IN ("N/A", "None") THEN ATTIRE2=2;

/*BIKEPARKING*/
IF BIKEPARKING="FALSE" THEN BIKEPARKING2=0;
IF BIKEPARKING="TRUE" THEN BIKEPARKING2=1;
IF BIKEPARKING IN ("N/A","None") THEN BIKEPARKING2=2;

/*CATERS*/
IF CATERS="FALSE" THEN CATERS2=0;
IF CATERS="TRUE" THEN CATERS2=1;
IF CATERS IN ("N/A","None") THEN CATERS2=2;

/*CITY*/
/*CLEANED UP HOW THE CITY LOOKED IN SAS*/ 
IF CITY IN ("East Pitts","Pittsburgh") THEN CITY2="Pittsburgh";
IF CITY IN ("Calgary","Northwest","Southeast") THEN CITY2="Calgary";
IF CITY IN ("North Toro","Toronto","Toronto Sc") THEN CITY2="Toronto";
IF CITY IN ("Charlotte") THEN CITY2="Charlotte";
IF CITY IN ("Phoenix","Phoenix Va") THEN CITY2="Phoenix";
IF CITY IN ("Las Vegas","N Las Vega","N. Las Veg","North Las","South Las") THEN CITY2="Las Vegas";
IF CITY IN ("Madison") THEN CITY2="Madison";
IF CITY IN ("Cleveland","East Cleve") THEN CITY2="Cleveland";

/*CREDITCARDS*/
IF CREDITCARDS="FALS" THEN CREDITCARDS2=0;
IF CREDITCARDS="TRUE" THEN CREDITCARDS2=1;
IF CREDITCARDS IN ("N/A","None") THEN CREDITCARDS2=2;

/*DELIVERY*/
IF DELIVERY="FALSE" THEN DELIVERY2=0;
IF DELIVERY="TRUE" THEN DELIVERY2=1;
IF DELIVERY IN ("N/A","None") THEN DELIVERY2=2;

/*GOODFORGROUPS*/
IF GOODFORGROUPS="FALSE" THEN GOODFORGROUPS2=0;
IF GOODFORGROUPS="TRUE" THEN GOODFORGROUPS2=1;
IF GOODFORGROUPS IN ("N/A","None") THEN GOODFORGROUPS2=2;

/*GOODFORKIDS*/
IF GOODFORKIDS="FALSE" THEN GOODFORKIDS2=0;
IF GOODFORKIDS="TRUE" THEN GOODFORKIDS2=1;
IF GOODFORKIDS IN ("N/A","None") THEN GOODFORKIDS2=2;

/*NOISELEVEL*/
IF NOISELEVEL IN ("quiet","u'quiet'") THEN NOISELEVEL2=0;
IF NOISELEVEL IN ("average","u'average'") THEN NOISELEVEL2=1;
IF NOISELEVEL IN ("loud","u'loud'","very_loud","u'very_lou") THEN NOISELEVEL2=2;
IF NOISELEVEL IN ("N/A","None") THEN NOISELEVEL2=3;

/*OUTDOORSEATING*/
IF OUTDOORSEATING="FALSE" THEN OUTDOORSEATING2=0;
IF OUTDOORSEATING="TRUE" THEN OUTDOORSEATING2=1;
IF OUTDOORSEATING IN ("N/A","None") THEN OUTDOORSEATING2=2;

/*PRICERANGE*/
/*IF PRICERANGE=0 THEN PRICERANGE2=.;*/
/*ELSE PRICERANGE2=PRICERANGE;*/

/*RESERVATIONS*/
IF RESERVATIONS="FALSE" THEN RESERVATIONS2=0;
IF RESERVATIONS="TRUE" THEN RESERVATIONS2=1;
IF RESERVATIONS IN ("N/A","None") THEN RESERVATIONS2=2;

/*TAKEOUT*/
IF TAKEOUT="FALSE" THEN TAKEOUT2=0;
IF TAKEOUT="TRUE" THEN TAKEOUT2=1;
IF TAKEOUT IN ("N/A","None") THEN TAKEOUT2=2;

/*TV*/
IF TV="FALSE" THEN TV2=0;
IF TV="TRUE" THEN TV2=1;
IF TV IN ("N/A","None") THEN TV2=2;

/*WIFI*/
IF WIFI IN ("no","u'no'") THEN WIFI2=0;
IF WIFI IN ("free","u'free'","paid","u'paid'") THEN WIFI2=1;
IF WIFI IN ("N/A","None") THEN WIFI2=2;

/*9 AMBIENCE VARIABLES*/
IF TOURISTY="FALSE" THEN TOURISTY2=0;
IF TOURISTY="TRUE" THEN TOURISTY2=1;
IF TOURISTY IN ("N/A","") THEN TOURISTY2=2;

IF CASUAL="FALSE" THEN CASUAL2=0;
IF CASUAL="TRUE" THEN CASUAL2=1;
IF CASUAL IN ("N/A","") THEN CASUAL2=2;

IF ROMANTIC="FALSE" THEN ROMANTIC2=0;
IF ROMANTIC="TRUE" THEN ROMANTIC2=1;
IF ROMANTIC IN ("N/A","") THEN ROMANTIC2=2;

IF INTIMATE="FALSE" THEN INTIMATE2=0;
IF INTIMATE="TRUE" THEN INTIMATE2=1;
IF INTIMATE IN ("N/A","") THEN INTIMATE2=2;

IF CLASSY="FALSE" THEN CLASSY2=0;
IF CLASSY="TRUE" THEN CLASSY2=1;
IF CLASSY IN ("N/A","") THEN CLASSY2=2;

IF HIPSTER="FALSE" THEN HIPSTER2=0;
IF HIPSTER="TRUE" THEN HIPSTER2=1;
IF HIPSTER IN ("N/A","") THEN HIPSTER2=2;

IF DIVEY="FALSE" THEN DIVEY2=0;
IF DIVEY="TRUE" THEN DIVEY2=1;
IF DIVEY IN ("N/A","") THEN DIVEY2=2;

IF TRENDY="FALSE" THEN TRENDY2=0;
IF TRENDY="TRUE" THEN TRENDY2=1;
IF TRENDY IN ("N/A","") THEN TRENDY2=2;

IF UPSCALE="FALSE" THEN UPSCALE2=0;
IF UPSCALE="TRUE" THEN UPSCALE2=1;
IF UPSCALE IN ("N/A","") THEN UPSCALE2=2;

/*5 BUSINESSPARKING VARIABLES*/
IF GARAGE="FALSE" THEN GARAGE2=0;
IF GARAGE="TRUE" THEN GARAGE2=1;
IF GARAGE IN ("N/A","") THEN GARAGE2=2;

IF STREET="FALSE" THEN STREET2=0;
IF STREET="TRUE" THEN STREET2=1;
IF STREET IN ("N/A","") THEN STREET2=2;

IF VALIDATED="FALSE" THEN VALIDATED2=0;
IF VALIDATED="TRUE" THEN VALIDATED2=1;
IF VALIDATED IN ("N/A","") THEN VALIDATED2=2;

IF LOT="FALSE" THEN LOT2=0;
IF LOT="TRUE" THEN LOT2=1;
IF LOT IN ("N/A","") THEN LOT2=2;

IF VALET="FALSE" THEN VALET2=0;
IF VALET="TRUE" THEN VALET2=1;
IF VALET IN ("N/A","") THEN VALET2=2;

/*6 GOODFORMEAL VARIABLES*/
IF DESSERT="FALSE" THEN DESSERT2=0;
IF DESSERT="TRUE" THEN DESSERT2=1;
IF DESSERT IN ("N/A","") THEN DESSERT2=2;

IF LATENIGHT="FALSE" THEN LATENIGHT2=0;
IF LATENIGHT="TRUE" THEN LATENIGHT2=1;
IF LATENIGHT IN ("N/A","") THEN LATENIGHT2=2;

IF LUNCH="FALSE" THEN LUNCH2=0;
IF LUNCH="TRUE" THEN LUNCH2=1;
IF LUNCH IN ("N/A","") THEN LUNCH2=2;

IF DINNER="FALSE" THEN DINNER2=0;
IF DINNER="TRUE" THEN DINNER2=1;
IF DINNER IN ("N/A","") THEN DINNER2=2;

IF BRUNCH="FALSE" THEN BRUNCH2=0;
IF BRUNCH="TRUE" THEN BRUNCH2=1;
IF BRUNCH IN ("N/A","") THEN BRUNCH2=2;

IF BREAKFAST="FALSE" THEN BREAKFAST2=0;
IF BREAKFAST="TRUE" THEN BREAKFAST2=1;
IF BREAKFAST IN ("N/A","") THEN BREAKFAST2=2;

RUN;

PROC SQL NOPRINT; 

/*HERE I AM ADDING SUPPLEMENTAL VARIABLES FOR CATEGORIES, TO SEE IF ANY OF THEM ARE SIGNIFICANT IN DETERMINING RESTAURANT SUCCESS*/ 
CREATE TABLE YELP3 AS
SELECT	*,
		IFN(categories LIKE ('%Bars%'),1,0) as BARS,
		IFN(categories LIKE ('%Nightlife%'),1,0) as NIGHTLIFE,
		IFN(categories LIKE ('%Pizza%'),1,0) as PIZZA,
		IFN(categories LIKE ('%American%'),1,0) as AMERICAN,
		IFN(categories LIKE ('%Tea%'),1,0) as TEA,
		IFN(categories LIKE ('%Sandwiches%'),1,0) as SANDWICHES,
		IFN(categories LIKE ('%Mexican%'),1,0) as MEXICAN,
		IFN(categories LIKE ('%Burgers%'),1,0) as BURGERS
FROM YELP2;

QUIT;

/*DROPPING THE PREVIOUS VERSIONS OF EACH VARIABLE THAT WE DON'T NEED*/
/*THERE ARE AGAIN 44 VARS, WHICH ALIGNS WITH YELP*/ 
DATA YELP4;
SET YELP3;
DROP	ALCOHOL ATTIRE BIKEPARKING CATERS CITY
		CREDITCARDS DELIVERY GOODFORGROUPS GOODFORKIDS NOISELEVEL 
		OUTDOORSEATING /*PRICERANGE*/ RESERVATIONS TAKEOUT TV 
		WIFI TOURISTY CASUAL ROMANTIC INTIMATE 
		CLASSY HIPSTER DIVEY TRENDY UPSCALE 
		GARAGE STREET VALIDATED LOT VALET 
		DESSERT LATENIGHT LUNCH DINNER BRUNCH 
		BREAKFAST;
RUN;

DATA YELP5;
SET YELP4;
/*MAKING STAR1, WHICH IS BINARY*/
IF STARS<4 THEN STARS1=0;
ELSE STARS1=1;
/*MAKING STARS 2. A CATEGORICAL VARIABLE SO EACH VALUE HAS ITS OWN WHOLE NUMBER*/
IF STARS=1 THEN STARS2=0;
IF STARS=1.5 THEN STARS2=1;
IF STARS=2 THEN STARS2=2;
IF STARS=2.5 THEN STARS2=3;
IF STARS=3 THEN STARS2=4;
IF STARS=3.5 THEN STARS2=5;
IF STARS=4 THEN STARS2=6;
IF STARS=4.5 THEN STARS2=7;
IF STARS=5 THEN STARS2=8;
RUN;

/*OUTPUTTING A CLEAN DATASET WHICH WILL BE READ IN BY PYTHON*/ 

PROC EXPORT DATA= WORK.YELP5
            OUTFILE= "FD_SAS.csv" 
            DBMS=CSV LABEL REPLACE;
     PUTNAMES=YES;
RUN;

/*IMPORTANT - HOW YOU DEALT WITH THE MISSING VALUES*/ 
/*FOR MOST, SET THE MISSINGS TO 2*/
/*FOR 1, SET THE MISSINGS TO 3*/
/*FOR PRICE RANGE, IT WAS 0 IN PYTHON*/ 

/*THE REST OF MY CODE IS IN PYTHON, FOR FEATURE SELECTION AND MODELS*/ 
